// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicTacToe.Infrastructure.DataBase;

#nullable disable

namespace TicTacToe.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250213103409_ModifyGameEntity")]
    partial class ModifyGameEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicTacToe.Infrastructure.Entities.GameEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CurrentPlayer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ShouldAiMove")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("TicTacToe.Infrastructure.Entities.GameEntity", b =>
                {
                    b.OwnsMany("TicTacToe.Infrastructure.Entities.MoveEntity", "Moves", b1 =>
                        {
                            b1.Property<long>("GameEntityId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Col")
                                .HasColumnType("integer");

                            b1.Property<char>("MoveSymbol")
                                .HasColumnType("character(1)");

                            b1.Property<int>("Row")
                                .HasColumnType("integer");

                            b1.HasKey("GameEntityId", "Id");

                            b1.ToTable("Games");

                            b1.ToJson("Moves");

                            b1.WithOwner()
                                .HasForeignKey("GameEntityId");
                        });

                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
