services:
  backend:
    build:
      context: .
      dockerfile: TicTacToe.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: backend
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: TicTacToeDb
      POSTGRES_USER: user
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db_postgres
volumes:
  db-data: