name: .NET CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' 

      - name: Restore dependencies
        run: dotnet restore ./backend/TicTacToe/TicTacToe.sln

      - name: Build project
        run: dotnet build ./backend/TicTacToe/TicTacToe.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./backend/TicTacToe/TicTacToe.sln --no-build --verbosity normal